language: c
sudo: true
install: developers/cached-deps.sh

cache:
  directories:
    - script: $HOME/HOL
    
addons:
  apt:
    sources:
    - script: sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
    packages:
    - script: polyml
    - script: libpolyml-dev
    - script: g++
    
jobs:
  env: PATH=$PATH:$HOME/HOL/bin LD_LIBRARY_PATH=$HOME/polyml/lib
  include:
  - stage: init
    script: chmod +x developers/regression-dir.sh developers/regression-init.sh
  - script: developers/regression-init.sh
  - script: travis_wait 60 developers/regression-dir.sh semantics/ffi
  - script: travis_wait 60 developers/regression-dir.sh semantics
  - script: travis_wait 60 developers/regression-dir.sh semantics/proofs
  - script: travis_wait 60 developers/regression-dir.sh basis/pure
  - script: travis_wait 60 developers/regression-dir.sh translator
  - script: travis_wait 60 developers/regression-dir.sh compiler/parsing
  - script: travis_wait 60 developers/regression-dir.sh characteristic
  - script: travis_wait 60 developers/regression-dir.sh basis
  - script: travis_wait 60 developers/regression-dir.sh translator/monadic
  - script: travis_wait 60 developers/regression-dir.sh compiler/inference
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/reg_alloc
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/gc
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/asm
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/x64
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/arm6
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/arm8
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/mips
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/riscv
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/x64
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/arm6
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/arm8
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/mips
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/riscv
  - script: travis_wait 60 developers/regression-dir.sh compiler/parsing/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/inference/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/semantics
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/reg_alloc/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/x64/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/arm6/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/arm8/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/mips/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/encoders/riscv/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/x64/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/arm6/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/arm8/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/mips/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/backend/riscv/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/proofs
  - script: travis_wait 60 developers/regression-dir.sh candle/set-theory
  - script: travis_wait 60 developers/regression-dir.sh candle/syntax-lib
  - script: travis_wait 60 developers/regression-dir.sh candle/standard/syntax
  - script: travis_wait 60 developers/regression-dir.sh candle/standard/semantics
  - script: travis_wait 60 developers/regression-dir.sh candle/standard/monadic
  - script: travis_wait 60 developers/regression-dir.sh candle/standard/ml_kernel
  - script: travis_wait 60 developers/regression-dir.sh candle/standard/opentheory
  - script: travis_wait 60 developers/regression-dir.sh compiler/benchmarks
  - script: travis_wait 60 developers/regression-dir.sh examples
  - script: travis_wait 60 developers/regression-dir.sh examples/compilation
  - script: travis_wait 60 developers/regression-dir.sh examples/compilation/proofs
  - script: travis_wait 60 developers/regression-dir.sh translator/okasaki-examples
  - script: travis_wait 60 developers/regression-dir.sh translator/other-examples
  - script: travis_wait 60 developers/regression-dir.sh compiler/parsing/tests
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/translation
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/translation/x64
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/x64
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/x64/proofs
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/translation/riscv
  - script: travis_wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/riscv

