language: c
sudo: false
install: developers/cached-deps.sh
script: developers/regression-test.sh
env: PATH=$PATH:$HOME/HOL/bin LD_LIBRARY_PATH=$HOME/polyml/lib
cache:
  directories:
    - $HOME/HOL
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ xenial main " | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y -t xenial libpolyml-dev polyml
