language: c
sudo: true
install: developers/cached-deps.sh
script: developers/regression-test.sh
env: PATH=$PATH:$HOME/HOL/bin LD_LIBRARY_PATH=$HOME/polyml/lib
cache:
  directories:
    - $HOME/HOL
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
    packages:
    - polyml
    - libpolyml-dev
    - g++
    
