language: c
sudo: true
install: developers/cached-deps.sh

cache:
  directories:
    - $HOME/HOL
    
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
    packages:
    - polyml
    - libpolyml-dev
    - g++
    
script: 
  - chmod +x developers/regression-dir.sh developers/regression-init.sh
  - developers/regression-init.sh
  - travis-wait 60 travis-wait 60 developers/regression-dir.sh semantics/ffi
  - travis-wait 60 travis-wait 60 developers/regression-dir.sh semantics
  - travis-wait 60 developers/regression-dir.sh semantics/proofs
  - travis-wait 60 developers/regression-dir.sh basis/pure
  - travis-wait 60 developers/regression-dir.sh translator
  - travis-wait 60 developers/regression-dir.sh compiler/parsing
  - travis-wait 60 developers/regression-dir.sh characteristic
  - travis-wait 60 developers/regression-dir.sh basis
  - travis-wait 60 developers/regression-dir.sh translator/monadic
  - travis-wait 60 developers/regression-dir.sh compiler/inference
  - travis-wait 60 developers/regression-dir.sh compiler/backend/reg_alloc
  - travis-wait 60 developers/regression-dir.sh compiler/backend/gc
  - travis-wait 60 developers/regression-dir.sh compiler/backend
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/asm
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/x64
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/arm6
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/arm8
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/mips
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/riscv
  - travis-wait 60 developers/regression-dir.sh compiler/backend/x64
  - travis-wait 60 developers/regression-dir.sh compiler/backend/arm6
  - travis-wait 60 developers/regression-dir.sh compiler/backend/arm8
  - travis-wait 60 developers/regression-dir.sh compiler/backend/mips
  - travis-wait 60 developers/regression-dir.sh compiler/backend/riscv
  - travis-wait 60 developers/regression-dir.sh compiler/parsing/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/inference/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/semantics
  - travis-wait 60 developers/regression-dir.sh compiler/backend/reg_alloc/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/x64/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/arm6/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/arm8/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/mips/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/encoders/riscv/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/x64/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/arm6/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/arm8/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/mips/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/backend/riscv/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/proofs
  - travis-wait 60 developers/regression-dir.sh candle/set-theory
  - travis-wait 60 developers/regression-dir.sh candle/syntax-lib
  - travis-wait 60 developers/regression-dir.sh candle/standard/syntax
  - travis-wait 60 developers/regression-dir.sh candle/standard/semantics
  - travis-wait 60 developers/regression-dir.sh candle/standard/monadic
  - travis-wait 60 developers/regression-dir.sh candle/standard/ml_kernel
  - travis-wait 60 developers/regression-dir.sh candle/standard/opentheory
  - travis-wait 60 developers/regression-dir.sh compiler/benchmarks
  - travis-wait 60 developers/regression-dir.sh examples
  - travis-wait 60 developers/regression-dir.sh examples/compilation
  - travis-wait 60 developers/regression-dir.sh examples/compilation/proofs
  - travis-wait 60 developers/regression-dir.sh translator/okasaki-examples
  - travis-wait 60 developers/regression-dir.sh translator/other-examples
  - travis-wait 60 developers/regression-dir.sh compiler/parsing/tests
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/translation
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/translation/x64
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/x64
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/x64/proofs
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/translation/riscv
  - travis-wait 60 developers/regression-dir.sh compiler/bootstrap/compilation/riscv

env: PATH=$PATH:$HOME/HOL/bin LD_LIBRARY_PATH=$HOME/polyml/lib
